#!/bin/bash

docker buildx build --push --platform linux/amd64,linux/arm64 \
  --build-arg VCS_REF=`git rev-parse HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -t zarklord/nut-monitor:$* .
